# Copyright 2026- The Blackjax Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Smoke tests for the analytic_iid generation path.

Each test runs at tiny scale (2 chains × 50 draws) and validates:
1. The generated draws.npz loads and has the expected shape.
2. The generated summary_v2.json passes the quality gate.
3. Per-site mean is within 5σ of the committed GT mean (crude coherence check).
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from tuningfork.groundtruth._analytic_iid import generate_analytic_iid
from tuningfork.groundtruth._dispatch import committed_gt_dir, load_committed_summary

pytestmark = pytest.mark.slow

_ANALYTIC_MODELS = ["banana", "gmm_25", "ill_cond_50", "mvn_10", "neals_funnel"]

_SMOKE_N_CHAINS = 2
_SMOKE_N_DRAWS = 50


@pytest.mark.parametrize("model_name", _ANALYTIC_MODELS)
def test_analytic_iid_smoke(model_name: str, tmp_path: Path) -> None:
    """Smoke: analytic_iid generates gate-passing output with coherent means."""
    committed = load_committed_summary(model_name)
    committed_gt = committed_gt_dir(model_name)

    result = generate_analytic_iid(
        model_name,
        committed,
        tmp_path,
        smoke=True,
    )

    # --- schema checks ---
    assert result["schema_version"] == "gt_v2_multichain"
    assert result["generator"] == "analytic_iid"
    assert result["model_name"] == model_name
    assert result["n_chains"] == _SMOKE_N_CHAINS
    assert result["n_draws_per_chain"] == _SMOKE_N_DRAWS

    # --- gate schema check (not gate pass — thresholds are for full 10×10k runs) ---
    # The quality gate fields must be present and internally consistent, but we
    # don't assert gate["passed"] here: at 2×50 draws, R̂ estimates are noisy
    # (fat-tailed models like neals_funnel can show R̂ > 1.01 by chance at n=100).
    gate = result["quality_gate"]
    assert "max_rhat" in gate, "quality_gate missing max_rhat"
    assert "min_bulk_ess" in gate, "quality_gate missing min_bulk_ess"
    assert "total_divergences" in gate, "quality_gate missing total_divergences"
    assert gate["total_divergences"] == 0, "analytic model should have 0 divergences"
    # R̂ should at least be finite and not wildly off (< 2.0 threshold for 50 draws)
    assert gate["max_rhat"] < 2.0, (
        f"{model_name}: max_rhat={gate['max_rhat']:.4f} ≥ 2.0 — "
        "something is wrong with the analytic sampler output"
    )

    # --- draws.npz shape check ---
    draws_path = tmp_path / "draws.npz"
    assert draws_path.exists(), f"draws.npz not written for {model_name}"
    # allow_pickle=True: committed draws.npz files were generated by older
    # scripts that saved JAX DeviceArrays directly, producing object-pickled
    # arrays.  Newly generated files are plain numpy (see _emit.py), but we
    # use allow_pickle=True uniformly so tests work against both old and new
    # artifacts.
    draws = np.load(str(draws_path), allow_pickle=True)
    for site in draws.files:
        shape = draws[site].shape
        assert (
            shape[0] == _SMOKE_N_CHAINS
        ), f"{model_name}.{site}: expected n_chains={_SMOKE_N_CHAINS}, got {shape[0]}"
        assert (
            shape[1] == _SMOKE_N_DRAWS
        ), f"{model_name}.{site}: expected n_draws={_SMOKE_N_DRAWS}, got {shape[1]}"

    # --- crude mean coherence vs committed GT ---
    # At smoke scale (2 chains × 50 draws = 100 samples), the new mean can
    # differ from the committed mean by many SE of the committed GT (which uses
    # 100k draws).  We check instead that new_mean is within 10 × committed_std
    # of committed_mean — a sanity check that the sampler is drawing from the
    # right distribution without being sensitive to the small sample size.
    committed_draws = np.load(str(committed_gt / "draws.npz"), allow_pickle=True)
    per_site = result["per_site"]
    for site in per_site:
        if site not in committed_draws.files:
            continue
        new_mean = np.asarray(per_site[site]["mean"]).ravel()
        comm_arr = committed_draws[site]
        comm_mean = comm_arr.reshape(-1, *comm_arr.shape[2:]).mean(axis=0).ravel()
        comm_std = comm_arr.reshape(-1, *comm_arr.shape[2:]).std(axis=0, ddof=1).ravel()
        # Check new_mean is within 10 × committed posterior std.
        # Flags clearly wrong outputs (e.g., all zeros, wrong scale) while
        # remaining robust to the high variance of 100-sample means.
        scale = np.maximum(comm_std, 1e-12)
        max_dev = float(np.max(np.abs(new_mean - comm_mean) / scale))
        assert max_dev < 10.0, (
            f"{model_name}.{site}: new mean deviates from committed GT by "
            f"{max_dev:.2f}× posterior std — sampler may be drawing from the "
            "wrong distribution"
        )
        # Also check means are finite (catches NaN/Inf in sampler output)
        assert np.all(
            np.isfinite(new_mean)
        ), f"{model_name}.{site}: new mean contains non-finite values"


def test_analytic_iid_verify_integration(tmp_path: Path) -> None:
    """Integration: coherence check passes on freshly generated analytic_iid.

    This test exercises the full generate → compute_summary_stats →
    between_chain_se → coherence z-score pipeline end-to-end.  Without it,
    a bug in compute_summary_stats (e.g. swapping the nc/ns axes when
    computing between_chain_se) could silently produce wrong SE values and
    never be caught.

    Note: the quality gate (R̂ ≤ 1.01) is NOT asserted here.  At 2×50 IID
    draws, rank-normalized split-R̂ is noisy and can exceed 1.01 by chance
    (observed: 1.12 in practice).  The gate is irrelevant to M1 — what
    matters is that the coherence z-score formula is exercised end-to-end.

    Uses z_threshold=5.0 (vs default 3.0): at smoke scale the per-chain SE
    is naturally large (only 2 chains), so z is small for a correct
    implementation; the inflated threshold avoids flakiness while still
    detecting a broken SE denominator (an axis swap would drastically alter
    the denominator, pushing z far outside even 10.0).
    """
    from tuningfork.groundtruth._verify import _check_coherence

    model_name = "mvn_10"
    committed = load_committed_summary(model_name)

    result = generate_analytic_iid(
        model_name,
        committed,
        tmp_path,
        smoke=True,
    )

    committed_summary = load_committed_summary(model_name)
    coh_pass, coh_results = _check_coherence(result, committed_summary, z_threshold=5.0)
    failing = [r for r in coh_results if not r["passed"]]
    assert coh_pass, (
        f"Coherence check failed on freshly generated analytic_iid for {model_name}. "
        f"Failing sites: {[{r['site']: round(r['max_z'], 2)} for r in failing]}. "
        "Possible cause: bug in compute_summary_stats between_chain_se "
        "(axis ordering, nc/ns swap) or coherence formula in _verify.py."
    )


def test_analytic_iid_output_files(tmp_path: Path) -> None:
    """Output directory contains exactly draws.npz and summary_v2.json."""
    committed = load_committed_summary("mvn_10")
    generate_analytic_iid("mvn_10", committed, tmp_path, smoke=True)

    written = {p.name for p in tmp_path.iterdir()}
    assert "draws.npz" in written, "draws.npz not written"
    assert "summary_v2.json" in written, "summary_v2.json not written"


def test_analytic_iid_custom_seed_differs(tmp_path: Path) -> None:
    """Two different seeds produce different draws (not bit-identical)."""
    committed = load_committed_summary("mvn_10")
    out1 = tmp_path / "seed1"
    out2 = tmp_path / "seed2"

    generate_analytic_iid("mvn_10", committed, out1, seed=1, smoke=True)
    generate_analytic_iid("mvn_10", committed, out2, seed=99, smoke=True)

    d1 = np.load(str(out1 / "draws.npz"), allow_pickle=True)
    d2 = np.load(str(out2 / "draws.npz"), allow_pickle=True)
    site = d1.files[0]
    assert not np.allclose(
        d1[site], d2[site]
    ), "Different seeds produced identical draws — RNG not working correctly"
