"""503-D NCP Stochastic Volatility model — Phase 4 Block-D model #9 (P4.9).

Model class: Kim-Shephard-Chib (1998) stochastic volatility, NCP recursive AR(1).

Statistician verdict (TL-orchestrated, 2026-05-08):
    Approve-with-modifications. NCP-recursive AR(1) via lax.scan;
    phi Beta(20,1.5)-shifted; posteriordb_id=None.

    CRITICAL CORRECTION 1: No posteriordb cross-check available.
        Full posteriordb directory scan confirms no stochastic-volatility
        posterior with reference draws exists upstream (only GARCH(1,1),
        which is a different model class). Set posteriordb_id=None. Use
        Long-NUTS self-check only (split-R̂ gate).

    CRITICAL CORRECTION 2: phi prior must be Beta(20, 1.5) shifted to (-1, 1),
        NOT Uniform(-1, 1). Uniform places mass near the unit-root boundary
        causing sigma/sqrt(1-phi^2) geometry blowup. Beta(20, 1.5) shifted
        concentrates mass at phi in [0.87, 0.99] (Kim-Shephard-Chib 1998
        canonical prior for daily financial vol).

    CRITICAL CORRECTION 3: T = 500 exactly. Dim = 503
        = mu(1) + phi(1) + log_sigma(1) + h_raw(500).

    CRITICAL CORRECTION 4: Recursive NCP via jax.lax.scan is correct —
        algebraically equivalent to Stan's transformed_parameters block.

Parameterization (NCP recursive AR(1)):
    mu       ~ Normal(-10, 5)                      # mean log-volatility
    phi      ~ 2 * Beta(20, 1.5) - 1               # via TransformedDistribution
    sigma    ~ HalfNormal(0.5)                     # innovation scale
    h_raw    ~ Normal(0, 1)^T                      # NCP innovations

    h[0]  = mu + (sigma / sqrt(1 - phi^2)) * h_raw[0]   # stationary init
    h[t]  = mu + phi * (h[t-1] - mu) + sigma * h_raw[t]  # t >= 1

    returns[t] ~ Normal(0, exp(h[t] / 2))

Unconstrained dimensionality = 503:
    mu(1) + phi(1, softplus-warped in (-1,1)) + log_sigma(1) + h_raw(500)

Data: synthetic, generated by tools/generate_stoch_vol.py.
    Parameters: mu=-10.0, phi=0.95, sigma=0.25, T=500, seed=20260508.
    Committed as bjx_bench/data/stoch_vol_returns.npy (float32, shape (500,)).

posteriordb_id = None:
    No upstream stochastic-volatility posterior with reference draws exists.
    Tier-A uses Long-NUTS self-check (split-R̂ < 1.01) only; no xcheck.

Tier-A budget:
    In-spawn verification: n_warmup=2000, n_samples=20000, 4 chains.
    Production cache: n_warmup=5000, n_samples=100000.
    (Escalated from radon's 1k/1k due to AR(1) autocorrelation; phi=0.95
    implies effective memory ~20 steps.)

Discrimination claim:
    NUTS vs MCLMC at 503-D AR(1). AR(1) creates tridiagonal precision in
    the latent space; MCLMC's continuous momentum may handle this more
    efficiently than diagonal-mass NUTS. Frame as "may favor MCLMC for
    long-memory AR chains" rather than guaranteed win. E-BFMI gate
    informative; if <0.3, may need to tighten phi prior further.

References:
    Kim, S., Shephard, N., & Chib, S. (1998). Stochastic Volatility:
        Likelihood Inference and Comparison with ARCH Models. Review of
        Economic Studies, 65(3), 361–393.
    PLAN_bjx_bench_phase4.md § "Block D", row P4.9 (stoch_vol).
"""

from __future__ import annotations

from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import numpyro
import numpyro.distributions as dist

from bjx_bench.model._base import Posterior

__all__ = [
    "ENTRY",
    "RETURNS",
    "T_LENGTH",
    "MU_TRUE",
    "PHI_TRUE",
    "SIGMA_TRUE",
]

# ---------------------------------------------------------------------------
# Model constants
# ---------------------------------------------------------------------------

#: Number of time steps (T = 500 per statistician verdict)
T_LENGTH: int = 500

#: Unconstrained dimensionality: mu(1) + phi(1) + log_sigma(1) + h_raw(500)
DIM: int = 3 + T_LENGTH  # = 503

#: Ground-truth parameters used to generate synthetic data
MU_TRUE: float = -10.0
PHI_TRUE: float = 0.95
SIGMA_TRUE: float = 0.25

#: Path to committed .npy data file
_NPY_PATH: Path = Path(__file__).parent.parent.parent / "data" / "stoch_vol_returns.npy"

# ---------------------------------------------------------------------------
# Load synthetic returns (shape: (500,), float32)
# ---------------------------------------------------------------------------

RETURNS: jnp.ndarray = jnp.array(np.load(_NPY_PATH), dtype=jnp.float32)

# Validate shape
assert RETURNS.shape == (
    T_LENGTH,
), f"Expected RETURNS shape ({T_LENGTH},), got {RETURNS.shape}"

# ---------------------------------------------------------------------------
# NumPyro model (NCP recursive AR(1) stochastic volatility)
# ---------------------------------------------------------------------------


def stoch_vol_model(returns: jnp.ndarray, T: int = T_LENGTH) -> None:
    """NumPyro model: 503-D NCP recursive AR(1) stochastic volatility.

    Kim-Shephard-Chib (1998) stochastic volatility model with non-centered
    parameterization and recursive AR(1) latent log-volatility via
    ``jax.lax.scan``. Posterior dim = 503 for T=500.

    Parameters
    ----------
    returns
        Observed returns array of shape (T,).
    T
        Number of time steps (500 for the synthetic stoch_vol dataset).

    Notes
    -----
    phi prior uses Beta(20, 1.5) shifted to (-1, 1) via TransformedDistribution
    (KSC 1998 canonical prior for daily financial vol). This concentrates mass
    at phi in [0.87, 0.99] and avoids unit-root boundary geometry blowup that
    would occur with Uniform(-1, 1).

    Latent log-volatility is initialised at the stationary distribution:
        h[0] ~ Normal(mu, sigma^2 / (1 - phi^2))

    Subsequent steps follow the AR(1) recursion:
        h[t] = mu + phi * (h[t-1] - mu) + sigma * h_raw[t]

    Likelihood: returns[t] ~ Normal(0, exp(h[t] / 2)).
    """
    mu = numpyro.sample("mu", dist.Normal(-10.0, 5.0))
    phi = numpyro.sample(
        "phi",
        dist.TransformedDistribution(
            dist.Beta(20.0, 1.5),
            dist.transforms.AffineTransform(loc=-1.0, scale=2.0),
        ),
    )
    sigma = numpyro.sample("sigma", dist.HalfNormal(0.5))

    h_raw = numpyro.sample("h_raw", dist.Normal(jnp.zeros(T), 1.0))

    def step(h_prev, h_raw_t):
        h_t = mu + phi * (h_prev - mu) + sigma * h_raw_t
        return h_t, h_t

    h0 = mu + (sigma / jnp.sqrt(1.0 - phi**2)) * h_raw[0]
    _, h_rest = jax.lax.scan(step, h0, h_raw[1:])
    h = jnp.concatenate([h0[None], h_rest])
    h = numpyro.deterministic("h", h)

    numpyro.sample("returns", dist.Normal(0.0, jnp.exp(h / 2.0)), obs=returns)


# ---------------------------------------------------------------------------
# Registry entry
# ---------------------------------------------------------------------------

ENTRY = Posterior(
    name="stoch_vol",
    dim=DIM,
    class_="latent_gaussian",
    tags=(
        "latent_gaussian",
        "state_space",
        "ar1",
        "ncp",
        "synthetic",
    ),
    numpyro_model=stoch_vol_model,
    model_args=(RETURNS,),
    model_kwargs={"T": T_LENGTH},
    posteriordb_id=None,  # no upstream SV posterior with reference draws
    citations=(
        "Kim, S., Shephard, N., & Chib, S. (1998). Stochastic Volatility: "
        "Likelihood Inference and Comparison with ARCH Models. "
        "Review of Economic Studies, 65(3), 361–393.",
        "PLAN_bjx_bench_phase4.md § 'Block D', row P4.9 (stoch_vol).",
    ),
    description=(
        "503-D NCP recursive AR(1) stochastic volatility (KSC 1998). "
        "T=500 synthetic returns, mu_true=-10, phi_true=0.95, sigma_true=0.25. "
        "Priors: mu~N(-10,5), phi~2*Beta(20,1.5)-1, sigma~HalfNormal(0.5), "
        "h_raw~N(0,1)^500 (NCP). "
        "posteriordb_id=None (no upstream reference draws; Long-NUTS self-check). "
        "Dim=503: mu(1)+phi(1)+log_sigma(1)+h_raw(500)."
    ),
)
